server {
    listen 80;
    server_name polypwngrand.ctf;

    location / {
        proxy_pass http://slots:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name manager.polypwngrand.ctf;

    location / {
        proxy_pass http://cams:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
