services:
  frontend:
    build: ./client
    image: furryos-frontend:latest
    restart: unless-stopped
    networks:
      - default
  backend:
    build: ./server
    image: furryos-backend:latest
    restart: unless-stopped
    networks:
      - default
