services:
  frontend:
    build: ./frontend
    image: janet-frontend:latest
    restart: unless-stopped
    networks:
      - default
  backend-server:
    build: ./backend
    image: janet-backend:latest
    restart: unless-stopped
    networks:
      - default
