server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /janet/ {
        proxy_pass http://backend-server:8000/janet/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /derek/ {
        proxy_pass http://backend-server:8000/derek/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
