services:
  php:
    build: ./php/
    image: star-command-php:latest
    networks:
      - default
    restart: unless-stopped

  mysql:
    build: ./mysql_scripts/
    image: star-command-mysql:latest
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "TheBiggestRootPasswordThatYouEverSeenSoNoOneCanBruteforceIt"
      MYSQL_DATABASE: starcommand
      MYSQL_USER: definitelynotzurg
      MYSQL_PASSWORD: "BuzzLighyearToStarCommand!DoYouReceiveMe?"
    restart: unless-stopped
